name: Docker Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform: [
                    "linux/amd64",
                    "linux/arm64"
                ]
                tag: [
                    3.8-slim,
                    3.8-slim-builder,
                    3.9-buster,
                    3.9-slim,
                    3.9-slim-builder,
                    3.10-buster,
                    3.10-slim,
                    3.10-slim-builder,
                    3.11-buster,
                    3.11-slim,
                    3.11-slim-builder,
                    3.12-bullseye,
                    3.12-slim,
                    3.12-slim-builder,
                    3.13-bullseye,
                    3.13-slim,
                    3.13-slim-builder,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Docker buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: sh build.sh ${{ matrix.tag }} ${{ matrix.platform }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
