name: Docker Push

on:
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                tag: [
                    3.8-slim,
                    3.8-slim-light,
                    3.9-buster,
                    3.9-slim,
                    3.9-slim-light,
                    3.10-buster,
                    3.10-slim,
                    3.10-slim-light,
                    3.11-buster,
                    3.11-slim,
                    3.11-slim-light,
                    3.12-bullseye,
                    3.12-slim,
                    3.12-slim-light,
                ]

        name: TAG-${{ matrix.tag }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: bash build.sh ${{ matrix.tag }}

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'